import { useLocation } from "react-router-dom";
import { useNavigate } from "react-router-dom";

function Cart() {

  const navigate =
    useNavigate();

  const location =
    useLocation();

  const cart =
    location.state?.cart || [];

  const total =
    location.state?.total || 0;

  return (

    <div className="min-h-screen bg-gray-100 p-4">

      <h1 className="text-3xl font-bold mb-6">

        Your Cart

      </h1>

      <div className="space-y-4">

        {cart.map((item) => (

          <div

            key={item._id}

            className="bg-white p-4 rounded-2xl shadow"

          >

            <h2 className="font-bold">

              {item.name}

            </h2>

            <p>

              Qty: {item.quantity}

            </p>

            <p>

              ₹
              {item.price *
                item.quantity}

            </p>

          </div>

        ))}

      </div>

      <div className="bg-white rounded-2xl p-5 shadow mt-6">

        <h2 className="text-2xl font-bold">

          Total: ₹{total}

        </h2>

        <div className="mt-4 p-3 bg-yellow-50 border-l-4 border-yellow-500 rounded-lg">

  <p className="text-sm text-gray-700">

    <span className="font-bold text-yellow-700">
      Note:
    </span>{" "}

    Prices displayed are
    <span className="font-bold text-red-600">
      {" "}exclusive of applicable GST{" "}
    </span>

    and service charges (if any). The
    <span className="font-bold text-blue-600">
      {" "}final bill{" "}
    </span>

    will be generated by the hotel at checkout.

  </p>

</div>

        <button

          onClick={() =>
            navigate(
              "/checkout",
              {
                state: {
                  cart,
                  total,
                },
              }
            )
          }

          className="w-full mt-4 bg-green-600 text-white py-3 rounded-xl"

        >

          Proceed To Confirm

        </button>

      </div>

    </div>

  );

}

export default Cart;